CLOSE ALL
SELECT * FROM DETALLE_FORMA_PAGO WHERE MONTOTOT > 0 AND MONTO=0 INTO CURSOR LASFIX

SELECT LASFIX
SCAN
	xqcomanda = LASFIX.COMANDA
	xqcuenta = LASFIX.CUENTA
	xidmod = lasfix.id
	
	SELECT SUM(MONTO) AS VARMONTO FROM DETALLE_FORMA_PAGO WHERE COMANDA =xqcomanda AND CUENTA=xqcuenta AND FORMA_PAGO<>1 INTO CURSOR LOSOTROS
	SELECT SUM(MONTOTOT) AS VAREFECTIVO,SUM(PROPINA) AS VARPROPINA FROM DETALLE_FORMA_PAGO WHERE COMANDA =xqcomanda AND CUENTA=xqcuenta AND FORMA_PAGO=1 INTO CURSOR ELEFE
	
	SELECT SUM(SUBTOTAL) AS SALDO FROM DETALLE_PAGO_COMANDA WHERE COMANDA =xqcomanda AND CUENTA=xqcuenta INTO CURSOR ELSALDO
	
	SELECT LOSOTROS
	IF !EOF()
		XVARMONTO = LOSOTROS.VARMONTO
	ENDIF
	
	SELECT ELEFE
	IF !EOF()
		XVAREFECTIVO = ELEFE.VAREFECTIVO
		XVARPROPINA = ELEFE.VARPROPINA
	ENDIF
	
	SELECT ELSALDO
	IF !EOF()
		xelsaldo = elsaldo.saldo
	ENDIF	
	
	XSALDO=xelsaldo-XVARMONTO
	
	IF XSALDO >= XVAREFECTIVO
		UPDATE DETALLE_FORMA_PAGO SET MONTO=XVAREFECTIVO ,CAMBIO = (XVAREFECTIVO-(XSALDO+XVARPROPINA)) WHERE ID = XIDMOD	
	ELSE 
		UPDATE DETALLE_FORMA_PAGO SET MONTO=XSALDO ,CAMBIO = (XVAREFECTIVO-(XSALDO+XVARPROPINA)) WHERE ID = XIDMOD	
	ENDIF
	
ENDSCAN
	
	
