***** proceso para enviar impresion,  XLLEVAR=0 ES COMANDA LOCAL, XLLEVAR=1 ES PARA LLEVAR
PARAMETERS xqcomanda


*----* Proceso nuevo de seleccion de datos para cocina

CREATE CURSOR BKCOMANDAC(;
	DESCRIPCION C(200), ;
	PAGADO C(13), ;
	SUBTOTAL N(10,2), ;
	COURSE INT, ;
	SILLAL C(5), ;
	PRODUCTO INT, ;
	DETALLE_COMANDA INT, ;
	ENVIADO L, SILLA INT, ;
	COMANDA INT, ;
	POWER INT, ;
	PARTICION INT, ;
	IDPOWER INT, ;
	ESPOWER INT, ;
	CANTIDAD INT, ;
	NOTAS C(250), ;
	SUBGRUPO I, ;
	UBICACION_PRINT I, ;
	REF N(10), ;
	UBICACION C(250), ;
	MESA C(10), ;
	MESERO C(100), ;
	TIPO N(10), ;
	GARROTERO I, ;
	REPLICAREN C(250), ;
	SALON I, ;
	PORSALON I, ;
	IDMESERO I, ;
	IDTOGO C(50), ;
	IDCUR I AUTOINC ;
)

SELECT IIF(ENVIADO,'** '+ALLTRIM(A.DESCRIPCION),a.DESCRIPCION) as DESCRIPCION , ;
ALLTRIM(STR(B.CANTIDAD-B.FACTURADO,10,2)) AS PAGADO,;
b.subtotal,;
B.COURSE, ;
ALLTRIM(STR(SILLA)) AS SILLAL,;
b.producto , ;
B.DETALLE_COMANDA, ;
ENVIADO, ;
B.SILLA, ;
B.COMANDA, ;
A.POWER, ;
B.PARTICION, ;
A.POWER AS ESPOWER, ;
b.ESEXTRA, ;
B.CANTIDAD, ;
B.NOTAS, ;
G.SUBGRUPO,;
G.UBICACION_PRINT,;
A.PRODUCTO AS REF,;
D.DIRECCION AS UBICACION,;
H.IDENTIFICADOR AS MESA,;
SPACE(100) AS MESERO,;
g.TIPO,;
e.garrotero,;
d.replicaren, ;
H.SALON AS SALON, ;
G.PORSALON, ;
E.MESERO AS IDMESERO, ;
b.IDPOWER, ;
E.IDTOGO ;
FROM PRODUCTO_MENU a, detalle_comanda b,UBICACION_PRINT D, COMANDA E, SUBGRUPO G, DETALLE_SALON H ;
where e.comanda = xqcomanda  AND B.comanda=e.comanda and a.producto=b.producto ;
AND a.SUBGRUPO=G.SUBGRUPO  AND IIF(b.course=0 OR b.course=g.course,G.UBICACION_PRINT=D.UBICACION_PRINT,b.course=d.course) ;
AND E.MESA=H.MESA AND !b.DETALLE AND EMPTY(b.POWER) AND EMPTY(ESEXTRA) AND !B.ENVIADO;
UNION ;
SELECT IIF(ENVIADO,'** '+ALLTRIM(A.DESCRIPCION),a.DESCRIPCION) as DESCRIPCION, ;
ALLTRIM(STR(B.CANTIDAD-B.FACTURADO,10,2)) AS PAGADO,;
b.subtotal,;
B.COURSE , ;
ALLTRIM(STR(SILLA)) AS SILLAL, ;
b.producto , ;
B.DETALLE_COMANDA, ;
b.ENVIADO,;
B.SILLA,;
B.COMANDA,;
0 AS POWER,;
B.PARTICION, ;
0 AS ESPOWER,;
b.ESEXTRA, ;
B.CANTIDAD, ;
B.NOTAS, ;
G.SUBGRUPO,;
G.UBICACION_PRINT,;
H.PRODUCTO AS REF,;
D.DIRECCION AS UBICACION, ;
I.IDENTIFICADOR AS MESA, ;
SPACE(100) AS MESERO, ;
g.TIPO, ;
e.garrotero, ;
d.replicaren, ;
I.SALON AS SALON, ;
G.PORSALON, ;
E.MESERO AS IDMESERO, ;
b.IDPOWER, ;
E.IDTOGO ;
FROM DETALLE_PRODUCTO a, detalle_comanda b,UBICACION_PRINT D, COMANDA E, SUBGRUPO G,PRODUCTO_MENU H, DETALLE_SALON I ;
where b.comanda = xqcomanda AND e.comanda=b.comanda AND H.PRODUCTO=A.PRODUCTO AND ;
b.PRODUCTO=a.DETALLE_PRODUCTO AND H.SUBGRUPO=G.SUBGRUPO  AND IIF(B.course=0 OR B.course=g.course,G.UBICACION_PRINT=D.UBICACION_PRINT,B.course=d.course);
AND E.MESA=I.MESA AND B.DETALLE AND EMPTY(b.POWER) AND EMPTY(B.ESEXTRA) AND !B.ENVIADO;
ORDER BY DETALLE_COMANDA desc;
INTO CURSOR BKCOMANDA1

SELECT BKCOMANDA1

SCAN
	
	DESCPART = ""
	
	IF BKCOMANDA1.PARTICION <> 0
		SELECT NOMBRE,DIVISOR FROM PARTICION WHERE ID=BKCOMANDA1.PARTICION INTO CURSOR LADESCPART
		
		SELECT LADESCPART
		GO TOP
		IF !EOF() AND LADESCPART.DIVISOR > 1
			DESCPART = " "+LADESCPART.NOMBRE
		ENDIF
	ENDIF
	
	SELECT BKCOMANDAC
	APPEND BLANK
	REPLACE DESCRIPCION WITH IIF(BKCOMANDA1.ESEXTRA=1,"EXTRA ", "")+ALLTRIM(BKCOMANDA1.DESCRIPCION) + DESCPART
	REPLACE PAGADO WITH BKCOMANDA1.PAGADO
	REPLACE SUBTOTAL WITH BKCOMANDA1.SUBTOTAL
	REPLACE COURSE WITH BKCOMANDA1.COURSE
	REPLACE SILLAL WITH BKCOMANDA1.SILLAL
	REPLACE PRODUCTO WITH BKCOMANDA1.PRODUCTO
	REPLACE DETALLE_COMANDA WITH BKCOMANDA1.DETALLE_COMANDA
	REPLACE ENVIADO WITH BKCOMANDA1.ENVIADO
	REPLACE SILLA WITH BKCOMANDA1.SILLA
	REPLACE COMANDA WITH BKCOMANDA1.COMANDA
	REPLACE POWER WITH BKCOMANDA1.POWER
	REPLACE PARTICION WITH BKCOMANDA1.PARTICION
	REPLACE ESPOWER WITH BKCOMANDA1.ESPOWER
	REPLACE CANTIDAD WITH BKCOMANDA1.CANTIDAD
	REPLACE NOTAS WITH BKCOMANDA1.NOTAS
	REPLACE SUBGRUPO WITH BKCOMANDA1.SUBGRUPO
	REPLACE UBICACION_PRINT WITH BKCOMANDA1.UBICACION_PRINT
	REPLACE REF WITH BKCOMANDA1.REF
	REPLACE UBICACION WITH BKCOMANDA1.UBICACION
	REPLACE MESA WITH BKCOMANDA1.MESA
	REPLACE MESERO WITH BKCOMANDA1.MESERO
	REPLACE TIPO WITH BKCOMANDA1.TIPO
	REPLACE garrotero WITH BKCOMANDA1.GARROTERO
	REPLACE replicaren WITH BKCOMANDA1.REPLICAREN
	REPLACE SALON WITH BKCOMANDA1.SALON
	REPLACE PORSALON WITH BKCOMANDA1.PORSALON
	REPLACE IDMESERO WITH BKCOMANDA1.IDMESERO
	REPLACE IDPOWER WITH BKCOMANDA1.IDPOWER
	REPLACE IDTOGO WITH BKCOMANDA1.IDTOGO
	
	SELECT IIF(ENVIADO,'** '+ALLTRIM(A.DESCRIPCION),a.DESCRIPCION) as DESCRIPCION , ;
	ALLTRIM(STR(B.CANTIDAD-B.FACTURADO,10,2)) AS PAGADO,;
	b.subtotal,;
	B.COURSE, ALLTRIM(STR(SILLA)) AS SILLAL,b.producto , B.DETALLE_COMANDA,ENVIADO,B.SILLA,B.COMANDA,A.POWER,B.PARTICION, B.IDPOWER, b.ESEXTRA, B.CANTIDAD,B.NOTAS ;
	FROM PRODUCTO_MENU a, detalle_comanda b ;
	where b.comanda = xqcomanda and a.producto=b.producto AND !DETALLE AND (b.IDPOWER=BKCOMANDA1.DETALLE_COMANDA OR b.IDEXTRA=BKCOMANDA1.DETALLE_COMANDA);
	UNION ALL ;
	SELECT SPACE(4)+IIF(ENVIADO,'** '+ALLTRIM(A.DESCRIPCION),a.DESCRIPCION) as DESCRIPCION, ;
	ALLTRIM(STR(B.CANTIDAD-B.FACTURADO,10,2)) AS PAGADO,;
	b.subtotal,;
	B.COURSE , ALLTRIM(STR(SILLA)) AS SILLAL,b.producto , B.DETALLE_COMANDA,ENVIADO,B.SILLA,B.COMANDA,0 AS POWER,B.PARTICION, B.IDPOWER, b.ESEXTRA, B.CANTIDAD,B.NOTAS ;
	FROM DETALLE_PRODUCTO a, detalle_comanda b ;
	where B.comanda = xqcomanda and a.DETALLE_producto=b.producto AND DETALLE AND (b.IDPOWER=BKCOMANDA1.DETALLE_COMANDA OR b.IDEXTRA=BKCOMANDA1.DETALLE_COMANDA);
	INTO CURSOR DETBKCOMANDA
		
	SELECT DETBKCOMANDA
	SCAN
		SELECT BKCOMANDAC
		APPEND BLANK
		REPLACE DESCRIPCION WITH SPACE(4)+IIF(DETBKCOMANDA.ESEXTRA=1,"EXTRA ", "")+ALLTRIM(DETBKCOMANDA.DESCRIPCION)
		REPLACE PAGADO WITH DETBKCOMANDA.PAGADO
		REPLACE SUBTOTAL WITH DETBKCOMANDA.SUBTOTAL
		REPLACE COURSE WITH DETBKCOMANDA.COURSE
		REPLACE SILLAL WITH DETBKCOMANDA.SILLAL
		REPLACE PRODUCTO WITH DETBKCOMANDA.PRODUCTO
		REPLACE DETALLE_COMANDA WITH DETBKCOMANDA.DETALLE_COMANDA
		REPLACE ENVIADO WITH DETBKCOMANDA.ENVIADO
		REPLACE SILLA WITH DETBKCOMANDA.SILLA
		REPLACE COMANDA WITH DETBKCOMANDA.COMANDA
		REPLACE POWER WITH DETBKCOMANDA.POWER
		REPLACE PARTICION WITH DETBKCOMANDA.PARTICION
		REPLACE IDPOWER WITH DETBKCOMANDA.IDPOWER
		REPLACE ESPOWER WITH 0
		REPLACE CANTIDAD WITH DETBKCOMANDA.CANTIDAD
		REPLACE NOTAS WITH DETBKCOMANDA.NOTAS
		REPLACE SUBGRUPO WITH BKCOMANDA1.SUBGRUPO
		REPLACE UBICACION_PRINT WITH BKCOMANDA1.UBICACION_PRINT
		REPLACE REF WITH BKCOMANDA1.REF
		REPLACE UBICACION WITH BKCOMANDA1.UBICACION
		REPLACE MESA WITH BKCOMANDA1.MESA
		REPLACE MESERO WITH BKCOMANDA1.MESERO
		REPLACE TIPO WITH BKCOMANDA1.TIPO
		REPLACE garrotero WITH BKCOMANDA1.GARROTERO
		REPLACE replicaren WITH BKCOMANDA1.REPLICAREN
		REPLACE SALON WITH BKCOMANDA1.SALON
		REPLACE PORSALON WITH BKCOMANDA1.PORSALON
		REPLACE IDMESERO WITH BKCOMANDA1.IDMESERO
		REPLACE IDTOGO WITH BKCOMANDA1.IDTOGO
		
		SELECT IIF(ENVIADO,'** '+ALLTRIM(A.DESCRIPCION),a.DESCRIPCION) as DESCRIPCION , ;
		ALLTRIM(STR(B.CANTIDAD-B.FACTURADO,10,2)) AS PAGADO,;
		b.subtotal,;
		B.COURSE, ALLTRIM(STR(SILLA)) AS SILLAL,b.producto , B.DETALLE_COMANDA,ENVIADO,B.SILLA,B.COMANDA,A.POWER,B.PARTICION, B.IDPOWER, b.ESEXTRA, B.CANTIDAD, B.NOTAS ;
		FROM PRODUCTO_MENU a, detalle_comanda b ;
		where b.comanda = xqcomanda and a.producto=b.producto AND !DETALLE AND b.IDEXTRA=DETBKCOMANDA.DETALLE_COMANDA;
		UNION ALL;
		SELECT SPACE(4)+IIF(ENVIADO,'** '+ALLTRIM(A.DESCRIPCION),a.DESCRIPCION) as DESCRIPCION, ;
		ALLTRIM(STR(B.CANTIDAD-B.FACTURADO,10,2)) AS PAGADO,;
		b.subtotal,;
		B.COURSE , ALLTRIM(STR(SILLA)) AS SILLAL,b.producto , B.DETALLE_COMANDA,ENVIADO,B.SILLA,B.COMANDA,0 AS POWER,B.PARTICION, B.IDPOWER, b.ESEXTRA, B.CANTIDAD, B.NOTAS ;
		FROM DETALLE_PRODUCTO a, detalle_comanda b ;
		where b.comanda = xqcomanda and a.DETALLE_producto=b.producto AND DETALLE AND b.IDEXTRA=DETBKCOMANDA.DETALLE_COMANDA;
		INTO CURSOR DETBKEXTRA
			
		SELECT DETBKEXTRA
		SCAN
			SELECT BKCOMANDAC
			APPEND BLANK
			REPLACE DESCRIPCION WITH SPACE(8)+IIF(DETBKEXTRA.ESEXTRA=1,"EXTRA ", "")+ALLTRIM(DETBKEXTRA.DESCRIPCION)
			REPLACE PAGADO WITH DETBKEXTRA.PAGADO
			REPLACE SUBTOTAL WITH DETBKEXTRA.SUBTOTAL
			REPLACE COURSE WITH DETBKEXTRA.COURSE
			REPLACE SILLAL WITH DETBKEXTRA.SILLAL
			REPLACE PRODUCTO WITH DETBKEXTRA.PRODUCTO
			REPLACE DETALLE_COMANDA WITH DETBKEXTRA.DETALLE_COMANDA
			REPLACE ENVIADO WITH DETBKEXTRA.ENVIADO
			REPLACE SILLA WITH DETBKEXTRA.SILLA
			REPLACE COMANDA WITH DETBKEXTRA.COMANDA
			REPLACE POWER WITH DETBKEXTRA.POWER
			REPLACE PARTICION WITH DETBKEXTRA.PARTICION
			REPLACE IDPOWER WITH DETBKEXTRA.IDPOWER
			REPLACE ESPOWER WITH 0
			REPLACE CANTIDAD WITH DETBKEXTRA.CANTIDAD
			REPLACE NOTAS WITH DETBKEXTRA.NOTAS
			REPLACE UBICACION_PRINT WITH BKCOMANDA1.UBICACION_PRINT
			REPLACE REF WITH BKCOMANDA1.REF
			REPLACE UBICACION WITH BKCOMANDA1.UBICACION
			REPLACE MESA WITH BKCOMANDA1.MESA
			REPLACE MESERO WITH BKCOMANDA1.MESERO
			REPLACE TIPO WITH BKCOMANDA1.TIPO
			REPLACE garrotero WITH BKCOMANDA1.GARROTERO
			REPLACE replicaren WITH BKCOMANDA1.REPLICAREN
			REPLACE SALON WITH BKCOMANDA1.SALON
			REPLACE PORSALON WITH BKCOMANDA1.PORSALON
			REPLACE IDMESERO WITH BKCOMANDA1.IDMESERO
			REPLACE IDTOGO WITH BKCOMANDA1.IDTOGO

		ENDSCAN
	ENDSCAN
	
ENDSCAN

SELECT BKCOMANDAC

SELECT A.COURSE,A.PRODUCTO,A.CANTIDAD,A.DESCRIPCION,A.NOTAS,A.SUBGRUPO,A.UBICACION_PRINT,A.REF,;
	A.UBICACION,A.COMANDA,A.MESA,A.MESERO,A.TIPO,A.garrotero,A.replicaren, ;
	A.SALON, A.PORSALON, A.IDMESERO, A.IDPOWER, A.POWER, IIF(A.POWER = 0,SPACE(200),;
	A.DESCRIPCION) AS NOMPOWER, A.NOTAS AS NOTAPOWER, ;
    A.IDTOGO, B.NOMBRE_LLEVAR, A.IDCUR ;
FROM BKCOMANDAC A, COMANDA B ;
WHERE A.COMANDA=B.COMANDA ORDER BY A.IDCUR ;
INTO CURSOR MISPENDIENTES READWRITE
*----* Proceso anterior

*SET STEP ON

*!*	SELECT A.COURSE,;
*!*		A.PRODUCTO,;
*!*		SUM (A.CANTIDAD) AS CANTIDAD,;
*!*		B.DESCRIPCION,;
*!*		A.NOTAS,;
*!*		G.SUBGRUPO,;
*!*		G.UBICACION_PRINT,;
*!*		A.PRODUCTO AS REF,;
*!*		D.DIRECCION AS UBICACION,;
*!*		E.COMANDA,;
*!*		H.IDENTIFICADOR AS MESA,;
*!*		SPACE(100) AS MESERO,;
*!*		g.TIPO,;
*!*		e.garrotero,;
*!*		d.replicaren, ;
*!*		H.SALON AS SALON, ;
*!*		G.PORSALON, ;
*!*		E.MESERO AS IDMESERO, ;
*!*		A.IDPOWER, ;
*!*		A.POWER, ;
*!*		E.IDTOGO, ;
*!*		A.DETALLE_COMANDA ;
*!*	FROM DETALLE_COMANDA A,PRODUCTO_MENU B,UBICACION_PRINT D, COMANDA E, SUBGRUPO G, DETALLE_SALON H;
*!*	WHERE !A.ENVIADO AND E.COMANDA=XQCOMANDA AND A.COMANDA=E.COMANDA AND A.PRODUCTO=B.PRODUCTO ;
*!*		AND B.SUBGRUPO=G.SUBGRUPO  AND IIF(a.course=0 OR a.course=g.course,G.UBICACION_PRINT=D.UBICACION_PRINT,a.course=d.course) ;
*!*		AND !A.DETALLE AND E.MESA=H.MESA;
*!*		AND B.POWER<>1 ;
*!*	GROUP BY 1,2,19,5 ;
*!*	UNION;
*!*	SELECT A.COURSE,A.PRODUCTO,SUM (A.CANTIDAD) AS CANTIDAD,B.DESCRIPCION,A.NOTAS,G.SUBGRUPO,G.UBICACION_PRINT,H.PRODUCTO AS REF,;
*!*		D.DIRECCION AS UBICACION,E.COMANDA,I.IDENTIFICADOR AS MESA,SPACE(100) AS MESERO,g.TIPO,e.garrotero,d.replicaren, ;
*!*		I.SALON AS SALON, G.PORSALON, E.MESERO AS IDMESERO, A.IDPOWER, A.POWER, E.IDTOGO, A.DETALLE_COMANDA ;
*!*	FROM DETALLE_COMANDA A,DETALLE_PRODUCTO B,UBICACION_PRINT D, COMANDA E, SUBGRUPO G,PRODUCTO_MENU H, DETALLE_SALON I;
*!*	WHERE !A.ENVIADO AND E.COMANDA=XQCOMANDA AND A.COMANDA=E.COMANDA AND H.PRODUCTO=B.PRODUCTO AND ;
*!*		A.PRODUCTO=B.DETALLE_PRODUCTO AND H.SUBGRUPO=G.SUBGRUPO  AND IIF(a.course=0 OR a.course=g.course,G.UBICACION_PRINT=D.UBICACION_PRINT,a.course=d.course);
*!*		 AND A.DETALLE AND E.MESA=I.MESA;
*!*	GROUP BY 1,2,19,5 ;
*!*	ORDER BY A.COURSE,G.TIPO,A.PRODUCTO,A.NOTAS;
*!*	INTO CURSOR MISPENDIENTES1 READWRITE

*!*	SELECT A.COURSE,A.PRODUCTO,A.CANTIDAD,A.DESCRIPCION,A.NOTAS,A.SUBGRUPO,A.UBICACION_PRINT,A.REF,;
*!*		A.UBICACION,A.COMANDA,A.MESA,A.MESERO,A.TIPO,A.garrotero,A.replicaren, ;
*!*		A.SALON, A.PORSALON, A.IDMESERO, A.IDPOWER, A.POWER, C.PARTICION, IIF(A.POWER = 0,SPACE(200),;
*!*		ALLTRIM(B.DESCRIPCION)+IIF(C.PARTICION=1,""," "+ALLTRIM(D.NOMBRE))) AS NOMPOWER, C.NOTAS AS NOTAPOWER, ;
*!*	    A.IDTOGO ;
*!*	FROM MISPENDIENTES1 A ;
*!*	LEFT JOIN PRODUCTO_MENU B ON A.POWER = B.PRODUCTO ;
*!*	LEFT JOIN DETALLE_COMANDA C ON A.IDPOWER = C.DETALLE_COMANDA ;
*!*	LEFT JOIN PARTICION D ON C.PARTICION = D.ID ;
*!*	ORDER BY A.COURSE,A.TIPO,A.IDPOWER,A.PRODUCTO,A.NOTAS;
*!*	INTO CURSOR MISPENDIENTES READWRITE

*----* fin de proceso anterior

XLLEVAR=0
SELECT MisPendientes
GO top
IF !EMPTY(IDTOGO)
   XLLEVAR=1
   xenviamenj=.t.
ENDIF

IF !EOF()
	SELECT empleado
	LOCATE FOR empleado=mispendientes.garrotero
	IF FOUND()
		xnamegarrotero=ALLTRIM(empleado.nombreS)
	ELSE
		xnamegarrotero=""
	ENDIF
	
	IF xllevar=0
		SELECT empleado
		LOCATE FOR empleado=mispendientes.IDMESERO
		IF FOUND()
			SELECT mispendientes
			REPLACE ALL MESERO WITH ALLTRIM(empleado.nombreS)
		ENDIF
	ELSE
		SELECT mispendientes
		REPLACE ALL MESERO WITH "MOSTRADOR"
	ENDIF
	
	SELECT MISPENDIENTES
	GO TOP
	
	SELECT SALON
	LOCATE FOR SALON=mispendientes.SALON
	IF FOUND()
		xnamesalon=ALLTRIM(salon.nombre)
	ELSE
		xnamesalon=""
	ENDIF
	
	SELECT * FROM turno WHERE !cerrado INTO CURSOR micurtur
	IF !EOF()
		STORE micurtur.noenvio+1 TO xelenvio
		STORE micurtur.turno TO xidturno
	ENDIF 
	
	SELECT mispendientes
	*DO FORM  MESAGEBOX WITH "SEGURO DE ENVIAR INFORMACION?"
	*XOPC=varmsgb 
	XOPC=6
	IF XOPC=6
		IF imp_cm=1 OR imp_cm=3
			
			SELECT MISPENDIENTES
			GO TOP
			SCAN
				IF PORSALON=1
					SELECT PRINTDIR FROM DETALLE_SALON_PRINT WHERE IDPRINT=MISPENDIENTES.UBICACION_PRINT AND SALON=MISPENDIENTES.SALON INTO CURSOR NEWPRINTDIR
					
					IF !EOF()
						SELECT MISPENDIENTES
						REPLACE UBICACION WITH NEWPRINTDIR.PRINTDIR
					ENDIF
				ENDIF
			ENDSCAN
			
			SELECT MISPENDIENTES
			
			SELECT DISTINCT UBICACION_PRINT, UBICACION AS UBICACION FROM MISPENDIENTES ORDER BY IDCUR INTO CURSOR MISUBICACIONES_UNO
			SELECT DISTINCT UBICACION_PRINT, REPLICAREN AS UBICACION FROM MISPENDIENTES ORDER BY IDCUR INTO CURSOR MISUBICACIONES_DOS
			
			SELECT UBICACION_PRINT,UBICACION FROM MISUBICACIONES_UNO WHERE !EMPTY(UBICACION) UNION;
			SELECT UBICACION_PRINT,UBICACION FROM MISUBICACIONES_DOS WHERE !EMPTY(UBICACION) INTO CURSOR MISUBICACIONES
			SCAN 
				SELECT * FROM MISPENDIENTES WHERE (UBICACION_PRINT = MISUBICACIONES.UBICACION_PRINT OR REPLICAREN=MISUBICACIONES.UBICACION) ORDER BY IDCUR INTO CURSOR CURDETALLE
				xprint='"'+ALLTRIM(misubicaciones.ubicacion)+'"'
				SET PRINTER TO NAME &xprint
				REPORT FORM ENVIO TO PRINTER NOCONS
				SET PRINTER TO 
			ENDSCAN
			
   	    ENDIF
		UPDATE turno SET noenvio=xelenvio WHERE turno=xidturno
		
		UPDATE DETALLE_COMANDA SET ENVIADO = .T. WHERE COMANDA=XQCOMANDA 
		
		SELECT DETALLE_COMANDA
		IF XLLEVAR=0
			=TABLEUPDATE(.T.)
	    ENDIF	
*!*			SELECT idtogo FROM comanda WHERE comanda = XQCOMANDA INTO CURSOR RTOGO
*!*			SELECT rtogo
*!*			IF !EMPTY(idtogo)
*!*				DO produccion_togo WITH rtogo.idtogo
*!*				UPDATE COMANDA SET produccion = 1 WHERE COMANDA=XQCOMANDA
*!*			ENDIF
		
		IF xllevar=0
			DO FORM AvisoBox WITH "!!COMANDA ENVIADA!!"
			Xmesalgo=1
			
		ENDIF
	ENDIF
ELSE
	DO FORM AvisoBox WITH "NO TIENE COMANDAS PENDIENTES DE ENVIAR!!"
ENDIF

*!*		IF XLLEVAR=1
*!*			MiProblema=0

*!*			*SELECT id_correla FROM salon WHERE salon=QSALON INTO CURSOR micorrelasalon
*!*			SELECT id_correla FROM sys01 WHERE idusuario=susuario INTO CURSOR micorrelasalon
*!*				
*!*			IF !EOF()
*!*				STORE micorrelasalon.id_correla TO xqcorrelauso
*!*			ELSE
*!*				STORE 1 TO xqcorrelauso
*!*			ENDIF

*!*			SELECT * FROM Corrala_fac WHERE id=xqcorrelauso INTO CURSOR MICURCFAC

*!*			XCORRELA=(MICURCFAC.FACTURA)
*!*			XSERIE=(MICURCFAC.SERIE)

*!*			*** Chequeo de validez de nuevo valor
*!*			SELECT factura FROM factura WHERE Factura=(xcorrela+1) AND Serie=XSERIE AND TIPO=1 INTO CURSOR ExisFac
*!*			IF !EOF()
*!*				STORE 1 TO Miproblema
*!*			ENDIF
*!*			*** Chequeo de que existe algun registro en blanco
*!*			SELECT factura
*!*			LOCATE FOR factura=0
*!*			IF FOUND()
*!*				SELECT * FROM corrala_fac INTO CURSOR  MeQuitaBlanco
*!*				SELECT factura
*!*				replace factura WITH Mequitablanco.quitablanco
*!*				UPDATE corrala_fac SET quitablanco=(Mequitablanco.quitablanco-1)
*!*			ENDIF
*!*		***************************************************************************************************	
*!*		SELECT * FROM corrala_fac INTO CURSOR elcorrela
*!*		xelcorr=elcorrela.id
*!*		SELECT * FROM rango_resolucion WHERE BETWEEN(DATE(),fecha_rfac,fecha_ven) AND id=xelcorr INTO CURSOR resolucion
*!*		SELECT resolucion
*!*		IF EOF()
*!*			DO FORM mesagebox WITH "No tiene Resolucion Ingresada"
*!*			THISFORM.Release
*!*		ELSE
*!*			IF resolucion.ultfactura=resolucion.al
*!*				DO FORM mesagebox WITH "No tienen un correlativo Activo"
*!*				THISFORM.Release
*!*			ELSE
*!*				xultfac=(resolucion.ultfactura+5)
*!*				IF xultfac>=resolucion.al
*!*					DO FORM mesagebox WITH "El Correlativo esta a punto de terminar"
*!*				ENDIF
*!*					IF MiProblema=1
*!*						DO FORM AVISOBOX WITH "El correlativo de la factura a imprimir ya existe verifique el correlativo."
*!*					ELSE
*!*						xmesalgo=0
*!*						DO pago_comanda
*!*						
*!*						IF xmesalgo=0
*!*							xmesalgo=0
*!*							THISFORM.RELEASE
*!*						ENDIF
*!*					ENDIF
*!*			ENDIF
*!*		ENDIF
*!*	ENDIF

